spring.application.name=empservice


# AWS - RDS Connection URL
spring.datasource.url=jdbc:mysql://inventory.cbi08c48209i.ap-south-1.rds.amazonaws.com:3306/emp?useSSL=true&serverTimezone=UTC

# Database Credentials
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}

# Driver Class Name (Optional for modern Spring Boot versions, as it auto-detects)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


#AWS - S3 details
cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
cloud.aws.region=ap-south-1
cloud.aws.s3bucketName=springboot-jars-s3-bucket-public