spring.application.name=customerapp

# Reduce logging level to make sure the application works with SAM local
# https://github.com/aws/serverless-java-container/issues/134
logging.level.root=WARN

aws.region=ap-south-1
#aws.access-key=${access-key}
aws.access-key=AKIA5Q4ASKUIZQMJRPPG
#aws.secret-key=${access-secret-key}
aws.secret-key=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